Update patch set 3
Patch Set 3:

(1 comment)

Hi Martin,

I tested this and everything went well except for one issue. I could not get the GUEST_TESTPMD_PARAMS to work correctly. I am unsure if I'm missing something?

(vsperfenv) [root@netqe16 vswitchperf]# ./vsperf pvp_cont --test-params="GUEST_SMP=['2'], GUEST_TESTPMD_PARAMS=['-l 0,1 -n 4 --socket-mem 512 -- --burst=64 -i --txqflags=0xf00 --disable-hw-vlan'];"
Traceback (most recent call last):
  File "./vsperf", line 691, in <module>
    main()
  File "./vsperf", line 484, in main
    args = parse_arguments()
  File "./vsperf", line 189, in parse_arguments
    args = vars(parser.parse_args())
  File "/usr/local/lib/python3.4/argparse.py", line 1721, in parse_args
    args, argv = self.parse_known_args(args, namespace)
  File "/usr/local/lib/python3.4/argparse.py", line 1753, in parse_known_args
    namespace, args = self._parse_known_args(args, namespace)
  File "/usr/local/lib/python3.4/argparse.py", line 1959, in _parse_known_args
    start_index = consume_optional(start_index)
  File "/usr/local/lib/python3.4/argparse.py", line 1899, in consume_optional
    take_action(action, args, option_string)
  File "/usr/local/lib/python3.4/argparse.py", line 1827, in take_action
    action(self, namespace, argument_values, option_string)
  File "./vsperf", line 92, in __call__
    ' \'key\'' % result)
argparse.ArgumentTypeError: expected '['GUEST_SMP', "['2'], GUEST_TESTPMD_PARAMS", "['-l 0,1 -n 4 --socket-mem 512 -- --burst", '64 -i --txqflags', "0xf00 --disable-hw-vlan']"]' to be of format 'key=val' or 'key'
(vsperfenv) [root@netqe16 vswitchperf]#

Patch-set: 3
Label: Verified=0